
###  list 조회(페이징 처리)
GET http://localhost:8080/api/3
Accept: application/json

### 단건 조회
GET http://localhost:8080/api/faqList/1
Accept: application/json

### createFaq 생성
POST http://localhost:8080/api/faqSave
Accept: application/json
Content-Type: application/json

< ./save.json

### createFaq 생성 - id까지 넣어보기 => 안된다..이거는 메서드를 새로 만들어 주던지 해야 할 듯
POST http://localhost:8080/api/faqSave
Accept: application/json
Content-Type: application/json

< ./idsave.json

### updateFaq 수정
POST http://localhost:8080/api/updateFaq/6
Accept: application/json
Content-Type: application/json

< ./update.json

### updateFaq 수정 - id 수정해볼까? => 이것도 안됨 메서드를 새로 만들어 주던지 해야 할 듯
POST http://localhost:8080/api/updateFaq/10
Accept: application/json
Content-Type: application/json

< ./updateid.json

### deleteFaq 삭제
DELETE http://localhost:8080/api/deleteFaq/4

### searchFaq 검색
GET http://localhost:8080/api/searchFaq/출
Accept: application/json

### sortFaq 정렬 - 기본 : DESC, sortFaq실행 후 : 기존값
GET http://localhost:8080/api/
Accept: application/json

### sortFaq 정렬
GET http://localhost:8080/api/sortFaq/ASC
Accept: application/json

### 작업해야할 순서
### 1. entityManager bean문제 해결 - jean202소스 보면서 해결
### 2. 지금까지 했던 메서드들 chrome에서 띄워서 호출하고 개발자 도구로 request response 보기 (네트워크 탭)

### 페이징
