package com.iconloop.posco.domain.dao;

import java.util.Date;
import javax.annotation.Generated;

/**
 * Database Table Remarks:
 *   faq
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table tbl_faq
 */
public class TblFaq {
    /**
     * Database Column Remarks:
     *   faq id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8181829+09:00", comments="Source field: tbl_faq.FAQ_ID")
    private Integer faqId;

    /**
     * Database Column Remarks:
     *   faq category id
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8221848+09:00", comments="Source field: tbl_faq.FAQ_CTGR_ID")
    private Integer faqCtgrId;

    /**
     * Database Column Remarks:
     *   open type(0:unopened, 1:opened)
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.823185+09:00", comments="Source field: tbl_faq.OPEN_TP")
    private Boolean openTp;

    /**
     * Database Column Remarks:
     *   subject
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.823185+09:00", comments="Source field: tbl_faq.SBJ")
    private String sbj;

    /**
     * Database Column Remarks:
     *   content
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.823185+09:00", comments="Source field: tbl_faq.CNTNT")
    private String cntnt;

    /**
     * Database Column Remarks:
     *   view count
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8241857+09:00", comments="Source field: tbl_faq.VIEW_CNT")
    private Integer viewCnt;

    /**
     * Database Column Remarks:
     *   registered date
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8241857+09:00", comments="Source field: tbl_faq.REG_DT")
    private Date regDt;

    /**
     * Database Column Remarks:
     *   modified date
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8251862+09:00", comments="Source field: tbl_faq.MOD_DT")
    private Date modDt;

    /**
     * Database Column Remarks:
     *   activate yn(0:no, 1:yes)
     */
    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8251862+09:00", comments="Source field: tbl_faq.ACT_YN")
    private Boolean actYn;

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8211841+09:00", comments="Source field: tbl_faq.FAQ_ID")
    public Integer getFaqId() {
        return faqId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8221848+09:00", comments="Source field: tbl_faq.FAQ_ID")
    public void setFaqId(Integer faqId) {
        this.faqId = faqId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8221848+09:00", comments="Source field: tbl_faq.FAQ_CTGR_ID")
    public Integer getFaqCtgrId() {
        return faqCtgrId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.823185+09:00", comments="Source field: tbl_faq.FAQ_CTGR_ID")
    public void setFaqCtgrId(Integer faqCtgrId) {
        this.faqCtgrId = faqCtgrId;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.823185+09:00", comments="Source field: tbl_faq.OPEN_TP")
    public Boolean getOpenTp() {
        return openTp;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.823185+09:00", comments="Source field: tbl_faq.OPEN_TP")
    public void setOpenTp(Boolean openTp) {
        this.openTp = openTp;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.823185+09:00", comments="Source field: tbl_faq.SBJ")
    public String getSbj() {
        return sbj;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.823185+09:00", comments="Source field: tbl_faq.SBJ")
    public void setSbj(String sbj) {
        this.sbj = sbj == null ? null : sbj.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8241857+09:00", comments="Source field: tbl_faq.CNTNT")
    public String getCntnt() {
        return cntnt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8241857+09:00", comments="Source field: tbl_faq.CNTNT")
    public void setCntnt(String cntnt) {
        this.cntnt = cntnt == null ? null : cntnt.trim();
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8241857+09:00", comments="Source field: tbl_faq.VIEW_CNT")
    public Integer getViewCnt() {
        return viewCnt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8241857+09:00", comments="Source field: tbl_faq.VIEW_CNT")
    public void setViewCnt(Integer viewCnt) {
        this.viewCnt = viewCnt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8241857+09:00", comments="Source field: tbl_faq.REG_DT")
    public Date getRegDt() {
        return regDt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8251862+09:00", comments="Source field: tbl_faq.REG_DT")
    public void setRegDt(Date regDt) {
        this.regDt = regDt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8251862+09:00", comments="Source field: tbl_faq.MOD_DT")
    public Date getModDt() {
        return modDt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8251862+09:00", comments="Source field: tbl_faq.MOD_DT")
    public void setModDt(Date modDt) {
        this.modDt = modDt;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8251862+09:00", comments="Source field: tbl_faq.ACT_YN")
    public Boolean getActYn() {
        return actYn;
    }

    @Generated(value="org.mybatis.generator.api.MyBatisGenerator", date="2021-07-14T07:33:51.8251862+09:00", comments="Source field: tbl_faq.ACT_YN")
    public void setActYn(Boolean actYn) {
        this.actYn = actYn;
    }
}